[project]
name = "sfguide-getting-started-with-snowflake-devops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "snowflake-cli>=2.8.2",
    "snowflake-core>=0.8.0",
    "snowflake-snowpark-python>=1.24.0",
]
